---
  - name: git install
    yum: name=git state=latest
    become: yes
  - name: ソースをgit clone
    git: repo=https://github.com/sstephenson/rbenv.git dest=/home/{{username}}/.rbenv 
  - name: ruby-build をgit clone
    git: repo=https://@github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  - name: 依存パッケージのインストール
    yum: name={{item}}  state=latest
    become: yes
    with_items:
      - libyaml
      - libyaml-devel
      - zlib
      - zlib-devel
      - readline
      - readline-devel
      - openssl
      - openssl-devel
      - libxml2
      - libxml2-devel
      - libxslt
      - libxslt-devel
      - gcc
      - glibc 
      - bzip2 
  - name: add .rbenv/bin to $PATH
    lineinfile: dest=/home/{{username}}/.bash_profile line='export PATH="$HOME/.rbenv/bin:$PATH"' regexp=PATH.*rbenv create=yes 
  - name: add rbenv init
    lineinfile: dest=/home/{{username}}/.bash_profile line='eval "$(rbenv init -)\"' regexp=eval.*rbenv create=yes
  - name: Ruby環境設定
    shell: /bin/bash -lc "rbenv install -v 2.2.3 && rbenv global 2.2.3 && rbenv rehash" chdir=/home/{{username}} 
